# file should be copied to /etc/sysctr.d/
# Check the setting value to check we are substituting correctly

# because of lgwebos wake on lan, we need somm settings
# https://www.devwithimagination.com/2020/06/15/homebridge-docker-and-wake-on-lan/
# https://www.openhab.org/addons/bindings/lgwebos/#configuration-for-wake-on-lan-in-docker 
net.ipv4.icmp_echo_ignore_broadcasts=0
net.ipv4.conf.all.bc_forwarding=1
#net.ipv4.conf.${interface}.bc_forwarding=1
# next for server-dev
net.ipv4.conf.br-ed34217cffb2.bc_forwarding=1
